name: Testing workflow

on:
  push:
    branches:
      - feature/version-bump

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message,'') }}
        run: echo "$COMMIT_MESSAGES"

      - name: testing boolean
        if: contains(join(github.event.commits.*.message ,''), '#skip') == false
        run: echo "hello worrrrld"
